apiVersion: v1
kind: Service
metadata:
  name: aspcore5-service
  labels:
   app: aspcore5-service
spec:
  selector:
    app: aspcore5
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer